### ISSUE TITLE
Firefox addon, cannot make changes in settings..

### ISSUE THREAD

**Issue by MelchiorGaspar** [breadgrocery/download-manager#9] opened 2024-12-09 23:47 UTC
I just installed the Firefox version of your Download Manager addon..
and right away I can't get any of the settings to change...
I click on Light appearance from auto and it doesn't work or change it...

but it seems to work in Google Chrome latest canary and release builds...

and other settings too.
will try a restart...
Firefox v133.0.0 and addon v1.0.9

and the downloads are not removed from the main download list though when I choose to use this addons delete from list option.

**Comment by MelchiorGaspar** [comment] 2024-12-10 01:18
I just tested out your download manager in 
Google Chrome canary build  (v133.0.6887.0)(Official Build)(canary)(64-bit)

the Chrome download manager download list disappears too when I delete the list from your addon list too,
chrome://downloads/

so it appears to be working correctly in Google Chrome.
so that just leaves it not working fully in Firefox v133.0.0/v133.0.3

**Comment by breadgrocery** [comment] 2024-12-10 04:56
Reproduced on my computer, thank you!

Reason:
Firefox seems to have shimmed a global `chrome` variable in the new version, causing the browser to misjudge and crash during the initialization phase.

**Comment by MelchiorGaspar** [comment] 2024-12-10 05:18
My pleasure to bug report as often as I can, when I find something I use, not working correctly..
Soo you can you fix it, right? lol ;) 

as it happens I only just started trying out your addon [Download Manager] for Mozilla Firefox and Google Chrome..
it seems ok I like it..

I loved an addon called Download Manager Tweak, which had info displayed for download location and full url of the download.
here is a screenshot of it via Waterfox classic which is old and still uses the XUL extension system for FIrefox.

![image](https://github.com/user-attachments/assets/c4f2ab24-30ba-48f5-85a5-4368b6749249)


is it possible for you to add some of its features to your download manager?
Please and thx.
mainly the download folder location, the url of where it came from and a one click clear all downloads with out deleting the 
file itself if possible.

**Comment by breadgrocery** [comment] 2024-12-10 05:38
My original intention was to keep the displayed information as concise as possible, because most of the time you won't need it.

- url
![image](https://github.com/user-attachments/assets/a01cf4c2-b33c-428c-a8b3-e101e32fca56)

- folder location
![image](https://github.com/user-attachments/assets/448e4028-b6f7-49b2-a9ba-f2843f3a4af8)

- clear all downloads with out deleting the file itself
![image](https://github.com/user-attachments/assets/eb1ddcc0-8181-4604-8670-ed8fb225a13b)
![image](https://github.com/user-attachments/assets/c7bca809-9b58-44bb-bd0b-041693df57bd)

**Comment by breadgrocery** [comment] 2024-12-10 07:54
Fixed in `v1.0.10` and published, try it out!

**Comment by MelchiorGaspar** [comment] 2024-12-10 10:08
alrighty then...
I thought I would ask is all. as far as a feature request goes.
ok this addon seems to be working now in Firefox. :D 

I am getting the update for Google Chrome now too.
ooh review time??? ooh my.. I may have to wait.

**Comment by MelchiorGaspar** [comment] 2024-12-10 10:17
ok in Firefox, the quick downloads panel is cleared but not the main downloads tab in Library view when I clear downloads from Download Manager addon sub window.

**Comment by breadgrocery** [comment] 2024-12-10 17:33
> Ok in Firefox, the quick downloads panel is cleared but not the main downloads tab in Library view when I clear downloads from Download Manager addon sub window.

This is a long-standing unresolved bug, probably dating back 9 years ago. 
There is nothing I can do about it, lol. 

You may interested in:

- [Handle old downloads in downloads API](https://bugzilla.mozilla.org/show_bug.cgi?id=1255507#c9)
- [browser.downloads.erase not removing from Library](https://bugzilla.mozilla.org/show_bug.cgi?id=1890187#c6)

**Closed by breadgrocery** 2024-12-10 17:33 UTC

**Comment by MelchiorGaspar** [comment] 2024-12-10 17:50
ooh! ok I guess.
"Web Extension APIs " suck compared to the older and more versatile XUL extension system
there are not that many extensions being made these days as great as in those days..

ty for a nice addon.
